---
title: "House prices"
author: "YOON HEO"
date: '2020 2 21 '
output: html_document
---

### Library
```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
library(corrplot)
library(MASS)
library(caret)
library(e1071)
library(gridExtra)
library(psych)
select <-dplyr::select
```

```{r, warning=FALSE, message=FALSE}
train <-read.csv("train.csv")
test <- read.csv("test.csv")
train$set <- "train"
test$set <- "test"
data <- dplyr::bind_rows(train,test)
data$set <- as.factor(data$set)

dim(data)

```

## Missing value check

```{r, fig.align='center', fig.height=9, fig.width=9}

missingValue <- data %>%
  select(-SalePrice) %>%
  summarise_all(funs( sum(is.na(.)) / n() )) %>%
  gather()

missingValue %>%
  filter(value > 0) %>%
  ggplot(aes(reorder(key,value), value, fill = key)) +
  geom_bar(stat ="identity") +
  geom_label(aes(label = paste0( round(value *100,2), "%" ))) +
  coord_flip() + xlab("") + ylab("") +
  theme_bw() +
  theme(legend.position = "none")
```

### 밑에서부터;;;

```{r, warning=FALSE, message=FALSE}

getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

## 0.03% 짜리 친구들

#BsmtFinSF1
data$BsmtFinSF1[is.na(data$BsmtFinSF1)] <- getmode(data$BsmtFinSF1)

#BsmtFinSF2
data$BsmtFinSF2[is.na(data$BsmtFinSF2)] <- getmode(data$BsmtFinSF2)

#BsmtUnfSF
data$BsmtUnfSF[is.na(data$BsmtUnfSF)] <- getmode(data$BsmtUnfSF)

# Electrical 
data$Electrical[is.na(data$Electrical)] <- getmode(data$Electrical)

# Exterior1st
data$Exterior1st[is.na(data$Exterior1st)] <- getmode(data$Exterior1st)

# Exterior2nd
data$Exterior2nd[is.na(data$Exterior2nd)] <- getmode(data$Exterior2nd)

# GarageArea
data$GarageArea[is.na(data$GarageArea)] <- getmode(data$GarageArea)

# GarageCars
data$GarageCars[is.na(data$GarageCars)] <- getmode(data$GarageCars)

# KitchenQual
data$KitchenQual[is.na(data$KitchenQual)] <- getmode(data$KitchenQual)

# SaleType
data$SaleType[is.na(data$SaleType)] <- getmode(data$SaleType)

# TotalBsmtSF
data$TotalBsmtSF[is.na(data$TotalBsmtSF)] <- getmode(data$TotalBsmtSF)

## 0.07% 짜리 친구들

# BsmtFullBath
data$BsmtFullBath[is.na(data$BsmtFullBath)] <- getmode(data$BsmtFullBath)

#BsmtHalfBath
data$BsmtHalfBath[is.na(data$BsmtHalfBath)] <- getmode(data$BsmtHalfBath)

# Functional
data$Functional[is.na(data$Functional)] <- getmode(data$Functional)

# Utilities
data$Utilities[is.na(data$Utilities)] <- getmode(data$Utilities)

## 6% 미만인 친구들

# MSZoning
data$MSZoning[is.na(data$MSZoning)] <- getmode(data$MSZoning)

# MasVnrArea
data$MasVnrArea[is.na(data$MasVnrArea)] <- getmode(data$MasVnrArea)

# MasVnrType
data$MasVnrType[is.na(data$MasVnrType)] <- getmode(data$MasVnrType)

## NA가 None을 의미하는 함수를 만듦
not_function <- function(df, col){
  df[,col] <- as.character(df[,col])
  df[is.na(df[,col]),col] <- "Nothing"
  df[,col] <- as.factor(df[,col])

  return(df[,col])
}

# BsmtFinType1
data$BsmtFinType1 <- not_function(data, "BsmtFinType1")

# BsmtFinType2
data$BsmtFinType2 <- not_function(data, "BsmtFinType2")

# BsmtQual
data$BsmtQual <- not_function(data, "BsmtQual")

# BsmtCond
data$BsmtCond <- not_function(data, "BsmtCond")

# BsmtExposure
data$BsmtExposure <- not_function(data, "BsmtExposure")

# GarageType
data$GarageType <- not_function(data, "GarageType")

# GarageCond
data$GarageCond <- not_function(data, "GarageCond")

# GarageFinish
data$GarageFinish <- not_function(data, "GarageFinish")

# GarageQual
data$GarageQual <- not_function(data, "GarageQual")

# GarageYrBlt // Median 값 넣을게요
data$GarageYrBlt[is.na(data$GarageYrBlt)] <- median(data$GarageYrBlt, na.rm = TRUE)

## 16.65% 

# LotFrontage
## Linear regression으로 값 넣겠습니다.
lm_data <- data %>%
  select_if(funs( sum(is.na(.)) == 0)) %>%
  select_if(funs( nlevels(.) > 5 | is.integer(.))) %>%
  select(-Id)

lm_data$LotFrontage <- data$LotFrontage

train_lm <- lm_data[!is.na(lm_data$LotFrontage),]
test_lm <- lm_data[is.na(lm_data$LotFrontage),]

## Linear regression Le's go
lm.fit <- lm(LotFrontage ~., data = train_lm)
step.lm.fit <- stepAIC(lm.fit, direction = "both",trace = FALSE)

test_lm$LotFrontage <- predict(step.lm.fit, test_lm)

data$LotFrontage[is.na(data$LotFrontage)] <- test_lm$LotFrontage

# FireplaceQu
data$FireplaceQu <- not_function(data, "FireplaceQu")

# Fence
data$Fence <- not_function(data, "Fence")

# Alley
data$Alley <- not_function(data, "Alley")

# MiscFeature // 피쳐 지우겠습니다.
data$MiscFeature <- NULL

# PoolQC 
data$PoolQC <- not_function(data, "PoolQC")
```

## Price density

```{r, echo=FALSE, fig.align='center', fig.width=9, fig.height=6}

p1 <- data %>%
  filter(set == "train") %>%
  ggplot(aes(SalePrice)) +
  geom_density() + xlab("SalePrice") +
  ggtitle("Sale Price Density") + 
  theme_bw()

p2 <- data %>%
  filter(set == "train") %>%
  ggplot(aes(log(SalePrice + 1))) +
  geom_density() + xlab("SalePrice") +
  ggtitle("Log Sale Price Density") + 
  theme_bw()

p3 <- data %>%
  filter(set == "train") %>%
  ggplot(aes(sample = SalePrice)) +
  stat_qq() + xlab("SalePrice") +
  stat_qq_line() +
  ggtitle("Sale Price qq plot") +
  theme_bw()

p4 <- data %>%
  filter(set == "train") %>%
  ggplot(aes(sample = log(SalePrice + 1))) +
  stat_qq() + xlab("Log SalePrice") +
  stat_qq_line() +
  ggtitle("Log Sale Price qq plot") +
  theme_bw()

grid.arrange(p1,p2,p3,p4, nrow = 2)
```

## Data manipulation

## 문자 -> 카테고리

```{r}
data <- data %>%
  mutate_if(is.character, as.factor)
```

## Train 변수 비율 이상한 것들 제거하기 

```{r}
check_data <- data %>%
  mutate_if(is.numeric, as.factor) %>%
  select(-SalePrice)

delete_col <- vector()
all_colname <- colnames(check_data)

j <- 1
for (i in 1:ncol(check_data)){
  if (sum(check_data[,i] == getmode(check_data[,i])) > 2770) {
    delete_col[j] <- all_colname[i]
    j <- j + 1
  }
}

data <- data[,!colnames(data) %in% delete_col]


data$PoolArea <- NULL
data$PoolQC <- NULL
data$GarageCond <- NULL
data$BsmtCond <- NULL
```

### change factor to integer

```{r}
data <- data %>%
  mutate(
    LotShape = case_when(
    data$LotShape == "IR3" ~ 1,
    data$LotShape == "IR2" ~ 2,
    data$LotShape == "IR1" ~ 3,
    data$LotShape == "Reg" ~ 4),
    LandContour = case_when(
      data$LandContour == "Low" ~ 1,
      data$LandContour == "HLS" ~ 2,
      data$LandContour == "Bnk" ~ 3,
      data$LandContour == "Lvl" ~ 4
    ),
    ExterQual = case_when(
      data$ExterQual == "Po" ~ 1,
      data$ExterQual == "Fa" ~ 2,
      data$ExterQual == "TA" ~ 3,
      data$ExterQual == "Gd" ~ 4,
      data$ExterQual == "Ex" ~ 5
    ),
    ExterCond = case_when(
      data$ExterCond == "Po" ~ 1,
      data$ExterCond == "Fa" ~ 2,
      data$ExterCond == "TA" ~ 3,
      data$ExterCond == "Gd" ~ 4,
      data$ExterCond == "Ex" ~ 5
    ),
    BsmtQual = case_when(
      data$BsmtQual == "Nothing" ~ 1,
      data$BsmtQual == "Po" ~ 2,
      data$BsmtQual == "Fa" ~ 3,
      data$BsmtQual == "TA" ~ 4,
      data$BsmtQual == "Gd" ~ 5,
      data$BsmtQual == "Ex" ~ 6
    ),
    BsmtExposure = case_when(
      data$BsmtExposure == "Nothing" ~ 1,
      data$BsmtExposure == "No" ~ 2,
      data$BsmtExposure == "Mn" ~ 3,
      data$BsmtExposure == "Av" ~ 4,
      data$BsmtExposure == "Gd" ~ 5
    ),
    BsmtFinType1 = case_when(
      data$BsmtFinType1 == "Nothing" ~ 1,
      data$BsmtFinType1 == "Unf" ~ 2,
      data$BsmtFinType1 == "LwQ" ~ 3,
      data$BsmtFinType1 == "Rec" ~ 4,
      data$BsmtFinType1 == "BLQ" ~ 5,
      data$BsmtFinType1 == "ALQ" ~ 6,
      data$BsmtFinType1 == "GLQ" ~ 7
    ),
    BsmtFinType2 = case_when(
      data$BsmtFinType2 == "Nothing" ~ 1,
      data$BsmtFinType2 == "Unf" ~ 2,
      data$BsmtFinType2 == "LwQ" ~ 3,
      data$BsmtFinType2 == "Rec" ~ 4,
      data$BsmtFinType2 == "BLQ" ~ 5,
      data$BsmtFinType2 == "ALQ" ~ 6,
      data$BsmtFinType2 == "GLQ" ~ 7
    ),
    HeatingQC = case_when(
      data$HeatingQC == "Po" ~ 1,
      data$HeatingQC == "Fa" ~ 2,
      data$HeatingQC == "TA" ~ 3,
      data$HeatingQC == "Gd" ~ 4,
      data$HeatingQC == "Ex" ~ 5
    ),
    KitchenQual = case_when(
      data$KitchenQual == "Po" ~ 1,
      data$KitchenQual == "Fa" ~ 2,
      data$KitchenQual == "TA" ~ 3,
      data$KitchenQual == "Gd" ~ 4,
      data$KitchenQual == "Ex" ~ 5
    ),
    GarageQual = case_when(
      data$GarageQual == "Nothing" ~ 1,
      data$GarageQual == "Po" ~ 2,
      data$GarageQual == "Fa" ~ 3,
      data$GarageQual == "TA" ~ 4,
      data$GarageQual == "Gd" ~ 5,
      data$GarageQual == "Ex" ~ 6
    )
  )

```

## Skewness check

```{r}
## skewness -2 < value < 2
check_data <- data %>%
  select_if(is.numeric) %>%
  select(-SalePrice)

delete_col <- vector()
all_colname <- colnames(check_data)

j <- 1
for (i in 1:ncol(check_data)){
  if (abs(skewness(check_data[,i])) > 2){
    delete_col[j] <- all_colname[i]
    j <- j + 1
  }
}

data %>%
  ggplot(aes((LotArea))) +
  geom_density()

data %>%
  ggplot(aes(LandContour)) +
  geom_density()

data %>%
  ggplot(aes(MasVnrArea)) +
  geom_density()

data %>%
  ggplot(aes(log(BsmtFinType2))) +
  geom_density()


data %>%
  ggplot(aes(BsmtFinSF2)) +
  geom_density()

data %>%
  ggplot(aes(BsmtHalfBath)) +
  geom_density()

## 그냥 냅두자 얘는
data %>%
  ggplot(aes(GarageQual)) +
  geom_density()

data %>%
  ggplot(aes(OpenPorchSF )) +
  geom_density()

data %>%
  ggplot(aes(EnclosedPorch )) +
  geom_density()

## 0이 너무 많은 값들은 어쩔 수가 없음....


data$LotArea <- log(data$LotArea)
data$BsmtFinType2 <- log(data$BsmtFinType2)

```

## Detection outlier

```{r}

data$SalePrice <- log(data$SalePrice)

train_out1 <- data %>%
  filter(set == "train") %>%
  select_if(is.numeric)

train_out2 <- data %>%
  filter(set == "train") %>%
  select_if(is.factor)

## tol=1e-20 붙여야 계산됨
maha <- mahalanobis(train_out1,colMeans(train_out1), cov(train_out1, use = "pairwise.complete.obs"), tol=1e-21)
cutoff <- qchisq(.999, ncol(train_out1))


noout1 <- train_out1[maha < cutoff , ]
noout2 <- train_out2[maha < cutoff , ]

new_data <- rbind( cbind(noout1, noout2), data[data$set=="test",])

```


## Just use Linear regression Model...
```{r}

train_data <- new_data %>%
  filter(set == "train") %>%
  select(-Id,-Exterior1st, -Functional)

test_data <- new_data %>%
  filter(set == "test") %>%
  select(-Id, -Exterior1st, -Functional)

train_data$set <- NULL
test_data$set <- NULL

## 리니어 모델 사용
lm.fit <- lm(SalePrice ~., data = train_data)
step.lm.fit <- stepAIC(lm.fit, direction = "both",trace = FALSE)

## 프리딕트 및 submit.csv 파일 만들기
test_data$SalePrice <- predict(step.lm.fit, test_data)
# submit <- data.frame(Id = test$Id, SalePrice = exp(test_data$SalePrice))

#write.csv(submit, "submit.csv", row.names = FALSE)

```

## Use SVM Linear Version

```{r}
svm.fit.radial <- svm(SalePrice~ ., data = train_data, cost = 3)

summary(svm.fit.radial)

test_data$SalePrice <- predict(svm.fit.radial, test_data)

# submit <- data.frame(Id = test$Id, SalePrice = exp(test_data$SalePrice))
# 
# write.csv(submit, "submit_svm.csv", row.names = FALSE)

```
















